export type FormatCategory =
  | 'documents'
  | 'images'
  | 'pdf'
  | 'audio'
  | 'video'
  | 'cad'
  | 'bim'
  | 'structural'
  | 'mechanical'
  | 'steel'
  | 'threed'
  | 'adobe'
  | 'ml'
  | 'aimodels'
  | 'datascience'
  | 'developer'
  | 'scientific'
  | 'archives';

export type FormatStatus = 'SUPPORTED' | 'PARTIAL' | 'COMING_SOON' | 'UNSUPPORTED';
export type SecurityLevel = 'SAFE' | 'LOW_RISK' | 'MEDIUM_RISK' | 'HIGH_RISK';

export interface FormatDefinition {
  extension: string;
  name: string;
  mimeType: string;
  category: FormatCategory;
  categoryLabel: string;
  description: string;
  inputSupport: boolean;
  outputSupport: boolean;
  supportedOutputs: string[];
  engine: string;
  status: FormatStatus;
  validation: string;
  securityLevel: SecurityLevel;
  maxFileSize: number; // in bytes
  multipageSupport: boolean;
  previewSupport: boolean;
  conversionNotes: string;
}

export const CATEGORY_LABELS: Record<FormatCategory, string> = {
  documents: 'Office Documents',
  images: 'Raster & Vector Images',
  pdf: 'PDF & Print Documents',
  audio: 'Audio Files',
  video: 'Video Files',
  cad: 'CAD Blueprints',
  bim: 'BIM & Architecture',
  structural: 'Structural & Civil Engineering',
  mechanical: 'Mechanical CAD',
  steel: 'Steel & Metal Fabrication',
  threed: '3D Geometry & Meshes',
  adobe: 'Adobe Creative Suite',
  ml: 'Machine Learning',
  aimodels: 'AI & Neural Models',
  datascience: 'Data Science & Tabular',
  developer: 'Developer & Code Files',
  scientific: 'Scientific & Technical Data',
  archives: 'Compressed Archives',
};

export const FORMAT_REGISTRY: FormatDefinition[] = [
  // ==================== 1. DOCUMENTS ====================
  {
    extension: 'docx',
    name: 'Microsoft Word Document',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Modern XML-based Microsoft Word document.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['pdf', 'txt', 'png', 'jpg'],
    engine: 'Mammoth & Docx Layout Engine',
    status: 'SUPPORTED',
    validation: 'ZIP container with word/document.xml',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Renders document structure, paragraphs, headings, bullet lists, and tables to PDF, high-res images, or text.',
  },
  {
    extension: 'doc',
    name: 'Legacy Microsoft Word',
    mimeType: 'application/msword',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Binary Microsoft Word 97-2003 document format.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'CFBF Compound Binary Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'OLE2 Compound Document signature (0xD0CF11E0)',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'Proprietary binary OLE2 container. Please save as modern .docx format for direct high-fidelity conversion.',
  },
  {
    extension: 'xlsx',
    name: 'Microsoft Excel Spreadsheet',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Modern XML-based Microsoft Excel workbook with formulas and worksheets.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['csv', 'json', 'tsv', 'pdf', 'png', 'jpg'],
    engine: 'ExcelJS Spreadsheet Engine',
    status: 'SUPPORTED',
    validation: 'ZIP container with xl/workbook.xml',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Exports active worksheets directly into CSV, JSON data arrays, TSV, or formatted visual PDF/PNG tables.',
  },
  {
    extension: 'xls',
    name: 'Legacy Microsoft Excel',
    mimeType: 'application/vnd.ms-excel',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Binary Microsoft Excel 97-2003 spreadsheet format (BIFF8).',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'BIFF8 Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'OLE2 Compound Document signature (0xD0CF11E0)',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'Legacy binary spreadsheet format. Export as modern .xlsx or .csv for direct conversion.',
  },
  {
    extension: 'pptx',
    name: 'Microsoft PowerPoint Presentation',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'XML-based Microsoft PowerPoint presentation slides.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['pdf', 'png'],
    engine: 'PresentationML Renderer (In Progress)',
    status: 'COMING_SOON',
    validation: 'ZIP container with ppt/presentation.xml',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'Slide layout vector rendering engine is in development. Direct PDF export arriving shortly.',
  },
  {
    extension: 'txt',
    name: 'Plain Text Document',
    mimeType: 'text/plain',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Universal UTF-8 plain text file.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['pdf', 'docx', 'png', 'jpg'],
    engine: 'Typography Document Engine & PDF-Lib',
    status: 'SUPPORTED',
    validation: 'UTF-8 character validation without binary null bytes',
    securityLevel: 'SAFE',
    maxFileSize: 20 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Paginates plain text into formatted printable PDFs or Microsoft Word DOCX documents with custom margins.',
  },
  {
    extension: 'md',
    name: 'Markdown Document',
    mimeType: 'text/markdown',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Lightweight formatted text with Markdown syntax.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['html', 'pdf', 'txt', 'docx'],
    engine: 'Markdown Lexer & PDF-Lib Engine',
    status: 'SUPPORTED',
    validation: 'UTF-8 text validation',
    securityLevel: 'SAFE',
    maxFileSize: 20 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Transforms Markdown headings, lists, code blocks, and emphasis into styled HTML, formatted PDF, or DOCX.',
  },
  {
    extension: 'html',
    name: 'HyperText Markup Language',
    mimeType: 'text/html',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Standard web document markup format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['pdf', 'txt'],
    engine: 'HTML Layout Engine',
    status: 'SUPPORTED',
    validation: 'Valid HTML tags (<html, <body, <div, etc.)',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Renders HTML markup and text into formatted PDF documents or extracts clean plain text.',
  },
  {
    extension: 'odt',
    name: 'OpenDocument Text',
    mimeType: 'application/vnd.oasis.opendocument.text',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Open standard document format used by LibreOffice.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'ODF Engine (Planned)',
    status: 'COMING_SOON',
    validation: 'ZIP container with mimetype application/vnd.oasis.opendocument.text',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'OpenDocument processing is planned. For current conversion, export to .docx or .pdf.',
  },
  {
    extension: 'rtf',
    name: 'Rich Text Format',
    mimeType: 'application/rtf',
    category: 'documents',
    categoryLabel: CATEGORY_LABELS.documents,
    description: 'Cross-platform rich text document specification.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'RTF Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'Starts with {\\rtf',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'RTF conversion pipeline is currently in development.',
  },

  // ==================== 2. PDF ====================
  {
    extension: 'pdf',
    name: 'Portable Document Format',
    mimeType: 'application/pdf',
    category: 'pdf',
    categoryLabel: CATEGORY_LABELS.pdf,
    description: 'Industry-standard vector and raster document format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'txt', 'docx'],
    engine: 'PDF-Lib, PDF.js & Canvas High-DPI Renderer',
    status: 'SUPPORTED',
    validation: 'Magic bytes %PDF- (0x25 0x50 0x44 0x46)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Full multi-page rasterization at 72-600 DPI, spatial text extraction, OCR analysis, split, merge, and compression.',
  },

  // ==================== 3. IMAGES ====================
  {
    extension: 'png',
    name: 'Portable Network Graphics',
    mimeType: 'image/png',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Lossless bitmap image format supporting alpha transparency.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['jpg', 'webp', 'pdf', 'gif', 'tiff', 'avif'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes 89 50 4E 47 0D 0A 1A 0A',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts losslessly with alpha channel handling, custom background colors, and DPI density controls.',
  },
  {
    extension: 'jpg',
    name: 'JPEG Image',
    mimeType: 'image/jpeg',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Standard lossy photographic compression format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'webp', 'pdf', 'tiff', 'avif'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes FF D8 FF',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts with configurable JPEG quality (1-100), subsampling, and metadata retention.',
  },
  {
    extension: 'webp',
    name: 'WebP Image',
    mimeType: 'image/webp',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Modern high-efficiency web image format developed by Google.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'pdf', 'tiff'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'RIFF....WEBP container header',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Provides lossy and lossless conversion between WebP and standard image formats.',
  },
  {
    extension: 'svg',
    name: 'Scalable Vector Graphics',
    mimeType: 'image/svg+xml',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'XML-based resolution-independent 2D vector graphics format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'Sharp SVG & Vector Rasterizer',
    status: 'SUPPORTED',
    validation: 'XML containing <svg root element',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Renders scalable vector paths, typography, and fills to crystal-clear high-DPI raster images or vector PDF.',
  },
  {
    extension: 'gif',
    name: 'Graphics Interchange Format',
    mimeType: 'image/gif',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Indexed 8-bit color bitmap image format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes GIF87a or GIF89a (0x47 0x49 0x46)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Extracts frames and renders to crisp PNG, JPG, or WebP.',
  },
  {
    extension: 'bmp',
    name: 'Windows Bitmap Image',
    mimeType: 'image/bmp',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Uncompressed device-independent bitmap format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes BM (0x42 0x4D)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts legacy uncompressed bitmaps into modern web formats.',
  },
  {
    extension: 'tiff',
    name: 'Tagged Image File Format',
    mimeType: 'image/tiff',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'High-color-depth printing and raster publishing image format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes II*. (0x49492A00) or MM.* (0x4D4D002A)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Renders high-bitrate TIFF scans to web-optimized PNG, JPG, or PDF.',
  },
  {
    extension: 'avif',
    name: 'AV1 Image File Format',
    mimeType: 'image/avif',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Next-generation image format compressed with AV1.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'Sharp High-Performance Image Pipeline',
    status: 'SUPPORTED',
    validation: 'ISOBMFF box with ftypavif brand',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Next-gen AVIF decompression to standard web formats with high color retention.',
  },
  {
    extension: 'ico',
    name: 'Windows Icon File',
    mimeType: 'image/x-icon',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Windows icon container format holding multiple resolutions.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp'],
    engine: 'Sharp Image Pipeline',
    status: 'SUPPORTED',
    validation: 'Icon reserved header 0x0000 0x0001',
    securityLevel: 'SAFE',
    maxFileSize: 15 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Extracts icon frames into standard PNG and WebP images.',
  },
  {
    extension: 'heic',
    name: 'High Efficiency Image Container',
    mimeType: 'image/heic',
    category: 'images',
    categoryLabel: CATEGORY_LABELS.images,
    description: 'Apple iOS camera high-efficiency image container format (HEIF).',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['jpg', 'png'],
    engine: 'libheif Decoder Engine',
    status: 'COMING_SOON',
    validation: 'ISOBMFF box with ftypheic/ftypmif1 brand',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Native HEIC decoder module is being packaged. Please export to JPEG on iOS devices for immediate conversion.',
  },

  // ==================== 4. AUDIO ====================
  {
    extension: 'mp3',
    name: 'MPEG-1 Audio Layer III',
    mimeType: 'audio/mpeg',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Standard lossy compressed digital audio format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['wav', 'flac', 'ogg', 'm4a', 'opus', 'aiff'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ID3v2 tag (0x49 0x44 0x33) or MPEG sync frame (0xFF 0xFB/0xFA)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Decodes and re-encodes with configurable bitrates (128k - 320k), stereo/mono channels, and sample rate conversion.',
  },
  {
    extension: 'wav',
    name: 'Waveform Audio File Format',
    mimeType: 'audio/wav',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Uncompressed linear PCM audio container.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'flac', 'ogg', 'm4a', 'opus', 'aiff'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'RIFF....WAVE container header',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts uncompressed PCM audio into compressed MP3, lossless FLAC, or web-optimized Ogg/Opus.',
  },
  {
    extension: 'flac',
    name: 'Free Lossless Audio Codec',
    mimeType: 'audio/flac',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Open-source lossless digital audio compression format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'ogg', 'm4a', 'aiff'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes fLaC (0x66 0x4C 0x61 0x43)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts lossless FLAC streams into lightweight MP3 or uncompressed WAV audio.',
  },
  {
    extension: 'm4a',
    name: 'MPEG-4 Audio',
    mimeType: 'audio/mp4',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Apple AAC/ALAC audio container.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'flac', 'ogg'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ftypM4A brand box',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Transcodes AAC/M4A streams into universal MP3 or uncompressed WAV.',
  },
  {
    extension: 'aac',
    name: 'Advanced Audio Coding',
    mimeType: 'audio/aac',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'High-efficiency lossy digital audio compression standard.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'flac', 'ogg'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ADTS syncword (0xFF 0xF1 or 0xFF 0xF9)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Decodes ADTS AAC audio streams into MP3 and uncompressed WAV.',
  },
  {
    extension: 'ogg',
    name: 'Ogg Vorbis Audio',
    mimeType: 'audio/ogg',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Open container format utilizing Vorbis lossy audio compression.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'flac', 'm4a'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'Magic bytes OggS (0x4F 0x67 0x67 0x53)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts Ogg Vorbis streams into MP3 or WAV audio.',
  },
  {
    extension: 'opus',
    name: 'Opus Interactive Audio',
    mimeType: 'audio/opus',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'IETF standard ultra-low-latency voice and music codec.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'flac'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'Ogg container with OpusHead packet (0x4F 0x70 0x75 0x73 0x48 0x65 0x61 0x64)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Transcodes Opus interactive audio into universal MP3 or WAV.',
  },
  {
    extension: 'aiff',
    name: 'Audio Interchange File Format',
    mimeType: 'audio/aiff',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Apple uncompressed audio file specification.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav', 'flac'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'FORM....AIFF container header',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts studio AIFF uncompressed recordings into MP3 or WAV.',
  },
  {
    extension: 'wma',
    name: 'Windows Media Audio',
    mimeType: 'audio/x-ms-wma',
    category: 'audio',
    categoryLabel: CATEGORY_LABELS.audio,
    description: 'Microsoft proprietary audio codec container.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp3', 'wav'],
    engine: 'FFmpeg Audio Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ASF header GUID (0x30 0x26 0xB2 0x75)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Decodes Windows Media Audio into universal MP3 and WAV.',
  },

  // ==================== 5. VIDEO ====================
  {
    extension: 'mp4',
    name: 'MPEG-4 Part 14 Video',
    mimeType: 'video/mp4',
    category: 'video',
    categoryLabel: CATEGORY_LABELS.video,
    description: 'Universal digital multimedia container format for video and audio.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['webm', 'mov', 'avi', 'mp3', 'wav', 'jpg', 'png'],
    engine: 'FFmpeg Video Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ISOBMFF box with ftyp brand (mp41, mp42, isom)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Transcodes video containers, extracts audio tracks to MP3/WAV, and captures keyframe thumbnails to JPG/PNG.',
  },
  {
    extension: 'webm',
    name: 'WebM Video',
    mimeType: 'video/webm',
    category: 'video',
    categoryLabel: CATEGORY_LABELS.video,
    description: 'Royalty-free open media file format designed for the web (VP8/VP9/AV1).',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp4', 'mov', 'mp3', 'wav', 'jpg', 'png'],
    engine: 'FFmpeg Video Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'EBML ID 0x1A 0x45 0xDF 0xA3 with DocType webm',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts WebM videos into H.264 MP4, extracts audio, or generates video thumbnails.',
  },
  {
    extension: 'mov',
    name: 'Apple QuickTime Movie',
    mimeType: 'video/quicktime',
    category: 'video',
    categoryLabel: CATEGORY_LABELS.video,
    description: 'Apple QuickTime multimedia container format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp4', 'webm', 'mp3', 'wav', 'jpg', 'png'],
    engine: 'FFmpeg Video Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'ftypqt brand or moov atom header',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Transcodes Apple QuickTime MOV files to universal H.264 MP4, WebM, or audio tracks.',
  },
  {
    extension: 'mkv',
    name: 'Matroska Video Container',
    mimeType: 'video/x-matroska',
    category: 'video',
    categoryLabel: CATEGORY_LABELS.video,
    description: 'Flexible open standard multimedia container holding video, audio, and subtitle streams.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp4', 'webm', 'mp3', 'wav', 'jpg'],
    engine: 'FFmpeg Video Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'EBML ID 0x1A 0x45 0xDF 0xA3 with DocType matroska',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts Matroska MKV containers into standard MP4 or extracts embedded audio tracks.',
  },
  {
    extension: 'avi',
    name: 'Audio Video Interleave',
    mimeType: 'video/x-msvideo',
    category: 'video',
    categoryLabel: CATEGORY_LABELS.video,
    description: 'Legacy Microsoft multimedia container format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['mp4', 'webm', 'mp3', 'wav'],
    engine: 'FFmpeg Video Processing Pipeline',
    status: 'SUPPORTED',
    validation: 'RIFF....AVI container header',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Transcodes legacy AVI files into modern H.264 MP4 or WebM.',
  },

  // ==================== 6. CAD ====================
  {
    extension: 'dxf',
    name: 'Drawing Exchange Format',
    mimeType: 'image/vnd.dxf',
    category: 'cad',
    categoryLabel: CATEGORY_LABELS.cad,
    description: 'Autodesk standard CAD data exchange format containing vector entities and layers.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['svg', 'pdf', 'png', 'jpg'],
    engine: 'AutoCAD DXF Vector Engine',
    status: 'SUPPORTED',
    validation: 'ASCII DXF SECTION / ENTITIES structure or 0\\nSECTION',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Directly parses 2D/3D CAD layers, polylines, circles, arcs, text, and dimensions into vector SVG, print-ready PDF, or high-DPI raster images.',
  },
  {
    extension: 'dwg',
    name: 'AutoCAD Drawing Database',
    mimeType: 'image/vnd.dwg',
    category: 'cad',
    categoryLabel: CATEGORY_LABELS.cad,
    description: 'Autodesk AutoCAD proprietary binary drawing database.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Autodesk RealDWG / LibreDWG Pipeline (Planned)',
    status: 'COMING_SOON',
    validation: 'Header starts with AC10 (AC1015, AC1018, AC1024, AC1027, AC1032)',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Proprietary binary drawing database. For instant high-fidelity conversion, export from AutoCAD or TrueView to .DXF, which is fully supported.',
  },
  {
    extension: 'dwf',
    name: 'Design Web Format',
    mimeType: 'model/vnd.dwf',
    category: 'cad',
    categoryLabel: CATEGORY_LABELS.cad,
    description: 'Autodesk 2D/3D design collaboration format.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'DWF XML/ZIP Container Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'Starts with (DWF V or ZIP container',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'DWF container support is in development. Please export drawings to DXF or PDF for current conversion.',
  },

  // ==================== 7. STEEL & METAL FABRICATION ====================
  {
    extension: 'nc',
    name: 'DSTV NC Steel Fabrication Data',
    mimeType: 'text/plain',
    category: 'steel',
    categoryLabel: CATEGORY_LABELS.steel,
    description: 'Standard DSTV numerical control data for structural steel cutting, drilling, and fabrication.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['dxf', 'svg', 'pdf', 'png', 'json'],
    engine: 'DSTV Structural Steel Fabrication Engine',
    status: 'SUPPORTED',
    validation: 'DSTV blocks ST / EN / AK / IK / BO',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Authentically parses structural steel profiles (HEA, IPE, UB, plates), cuts, and hole coordinates into 2D CAD DXF drawings, shop blueprints (SVG/PDF), or JSON schedules.',
  },
  {
    extension: 'dstv',
    name: 'DSTV Steel Standard File',
    mimeType: 'text/plain',
    category: 'steel',
    categoryLabel: CATEGORY_LABELS.steel,
    description: 'Deutscher Stahlbau-Verband structural steel fabrication numerical control file.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['dxf', 'svg', 'pdf', 'png', 'json'],
    engine: 'DSTV Structural Steel Fabrication Engine',
    status: 'SUPPORTED',
    validation: 'DSTV blocks ST / EN / AK / IK / BO',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Directly converts steel beam fabrication geometries and bolt hole patterns into CAD DXF, vector SVG, and detailed fabrication PDF sheets.',
  },
  {
    extension: 'mak',
    name: 'Bocad / Tekla Marking File',
    mimeType: 'text/plain',
    category: 'steel',
    categoryLabel: CATEGORY_LABELS.steel,
    description: 'Steel fabrication piece marking and cutting file.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['dxf', 'svg', 'pdf', 'json'],
    engine: 'DSTV Structural Steel Fabrication Engine',
    status: 'SUPPORTED',
    validation: 'DSTV standard marking blocks',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses steel member marks, weld preps, and flange hole patterns into CAD DXF and PDF fabrication drawings.',
  },
  {
    extension: 'gcode',
    name: 'CNC G-Code Toolpath',
    mimeType: 'text/x-gcode',
    category: 'steel',
    categoryLabel: CATEGORY_LABELS.steel,
    description: 'Standard RS-274 machine tool motion instructions for milling, laser cutting, and 3D printing.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['dxf', 'svg', 'pdf', 'png', 'json'],
    engine: 'G-Code Vector Toolpath Engine',
    status: 'SUPPORTED',
    validation: 'Contains G0, G1, G2, G3, M-codes motion commands',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses CNC toolpaths, coordinates, and feed rates into 2D/3D CAD DXF drawings, vector SVG diagrams, or PDF machine reports.',
  },
  {
    extension: 'tap',
    name: 'CNC Machine Tap File',
    mimeType: 'text/x-gcode',
    category: 'steel',
    categoryLabel: CATEGORY_LABELS.steel,
    description: 'CNC numerical control machine program.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['dxf', 'svg', 'pdf', 'json'],
    engine: 'G-Code Vector Toolpath Engine',
    status: 'SUPPORTED',
    validation: 'Contains G-code commands',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses CNC toolpaths into CAD DXF vectors and shop summaries.',
  },

  // ==================== 8. 3D FORMATS ====================
  {
    extension: 'obj',
    name: 'Wavefront 3D Model',
    mimeType: 'model/obj',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Open standard 3D geometry format containing vertices, texture coordinates, normals, and polygonal faces.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['stl', 'ply', 'png', 'jpg', 'pdf', 'svg'],
    engine: 'Universal 3D Mesh Engine',
    status: 'SUPPORTED',
    validation: 'ASCII mesh with v / vn / vt / f declarations',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Cross-converts between OBJ and binary/ASCII STL or PLY, and renders shaded isometric 3D views to PNG, SVG, or PDF.',
  },
  {
    extension: 'stl',
    name: 'Stereolithography 3D Mesh',
    mimeType: 'model/stl',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Standard 3D triangle surface mesh format used in additive manufacturing and 3D printing.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['obj', 'ply', 'png', 'jpg', 'pdf', 'svg'],
    engine: 'Universal 3D Mesh Engine',
    status: 'SUPPORTED',
    validation: 'Binary STL 80-byte header with facet count or ASCII solid ... endsolid',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts binary/ASCII STL meshes into Wavefront OBJ or PLY, and renders shaded isometric viewports to PNG, SVG, or PDF.',
  },
  {
    extension: 'ply',
    name: 'Polygon File Format',
    mimeType: 'model/ply',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Stanford triangle format for 3D scanners and point clouds/polygonal meshes.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['obj', 'stl', 'png', 'pdf', 'svg'],
    engine: 'Universal 3D Mesh Engine',
    status: 'SUPPORTED',
    validation: 'Starts with ply\\nformat ascii or binary',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses ASCII and binary PLY elements and face indices into OBJ, STL, and shaded isometric renders.',
  },
  {
    extension: '3mf',
    name: '3D Manufacturing Format',
    mimeType: 'model/3mf',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Modern XML-based 3D printing container specification.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['stl', 'obj', 'png', 'pdf'],
    engine: 'Universal 3D Mesh Engine',
    status: 'SUPPORTED',
    validation: 'ZIP package containing 3D/3dmodel.model XML',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Extracts 3D printing mesh vertices and triangles into STL, OBJ, and isometric renders.',
  },
  {
    extension: 'off',
    name: 'Object File Format',
    mimeType: 'model/off',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Geomview polygonal surface mesh format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['obj', 'stl', 'png', 'pdf'],
    engine: 'Universal 3D Mesh Engine',
    status: 'SUPPORTED',
    validation: 'Starts with OFF',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses OFF polygon vertices and face arrays directly into OBJ or STL.',
  },
  {
    extension: 'gltf',
    name: 'GL Transmission Format',
    mimeType: 'model/gltf+json',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'JSON-based 3D scene and model transmission format.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['obj', 'stl'],
    engine: 'GLTF Scene Parser (In Development)',
    status: 'COMING_SOON',
    validation: 'JSON containing asset.version and scene / meshes',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Full glTF scene graph conversion to OBJ/STL is in testing.',
  },
  {
    extension: 'glb',
    name: 'Binary glTF 3D Model',
    mimeType: 'model/gltf-binary',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Binary container format for complete 3D assets.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['obj', 'stl'],
    engine: 'GLB Binary Parser (In Development)',
    status: 'COMING_SOON',
    validation: 'Magic bytes glTF (0x67 0x6C 0x54 0x46)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Binary glTF processing is currently undergoing validation.',
  },
  {
    extension: 'fbx',
    name: 'Autodesk Filmbox',
    mimeType: 'application/octet-stream',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Autodesk 3D asset and animation exchange format.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Autodesk FBX SDK (External)',
    status: 'COMING_SOON',
    validation: 'Kaydara FBX Binary or ASCII header',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Proprietary binary animation format. For 3D conversion, export to OBJ or STL.',
  },
  {
    extension: 'blend',
    name: 'Blender Project File',
    mimeType: 'application/x-blender',
    category: 'threed',
    categoryLabel: CATEGORY_LABELS.threed,
    description: 'Native project file of Blender 3D creation suite.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Blender Core Engine',
    status: 'COMING_SOON',
    validation: 'Starts with BLENDER_v or BLENDER',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Blender project file containing complex procedural node networks. Export meshes from Blender as OBJ or STL for instant conversion.',
  },
  {
    extension: 'step',
    name: 'Standard for Exchange of Product Data',
    mimeType: 'application/step',
    category: 'mechanical',
    categoryLabel: CATEGORY_LABELS.mechanical,
    description: 'ISO 10303 boundary representation CAD exchange standard.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'OpenCASCADE Boundary BREP Engine (Planned)',
    status: 'COMING_SOON',
    validation: 'Starts with ISO-10303-21',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'NURBS boundary representation standard. Tessellate to STL or OBJ in CAD software for immediate mesh conversion.',
  },
  {
    extension: 'stp',
    name: 'STEP CAD Exchange File',
    mimeType: 'application/step',
    category: 'mechanical',
    categoryLabel: CATEGORY_LABELS.mechanical,
    description: 'ISO 10303 mechanical CAD model exchange file.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'OpenCASCADE Boundary BREP Engine (Planned)',
    status: 'COMING_SOON',
    validation: 'Starts with ISO-10303-21',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'STEP solid boundary format. Export as STL or OBJ for immediate mesh conversion.',
  },
  {
    extension: 'iges',
    name: 'Initial Graphics Exchange Specification',
    mimeType: 'model/iges',
    category: 'mechanical',
    categoryLabel: CATEGORY_LABELS.mechanical,
    description: 'ANSI standard mechanical surface exchange specification.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'IGES Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'Fixed column format with S/G/D/P/T record lines',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Legacy CAD surface format. Export as STL or DXF for direct processing.',
  },
  {
    extension: 'igs',
    name: 'IGES CAD Model',
    mimeType: 'model/iges',
    category: 'mechanical',
    categoryLabel: CATEGORY_LABELS.mechanical,
    description: 'Mechanical CAD surface wireframe model.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'IGES Parser (Planned)',
    status: 'COMING_SOON',
    validation: 'Column 73 has S, G, D, P, or T marker',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Legacy CAD format. Export as STL or DXF for direct processing.',
  },

  // ==================== 9. BIM & STRUCTURAL ENGINEERING ====================
  {
    extension: 'ifc',
    name: 'Industry Foundation Classes',
    mimeType: 'application/x-step',
    category: 'bim',
    categoryLabel: CATEGORY_LABELS.bim,
    description: 'OpenBIM building information modeling data exchange specification (ISO 16739).',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['json', 'txt'],
    engine: 'IFC OpenBIM Parser (Metadata Mode)',
    status: 'PARTIAL',
    validation: 'ISO-10303-21 STEP physical file containing IFCPROJECT / IFCSITE',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses IFC2X3 and IFC4 building structure, project hierarchy, storey counts, and element counts to structured JSON and TXT summaries.',
  },
  {
    extension: 'rvt',
    name: 'Autodesk Revit Project',
    mimeType: 'application/octet-stream',
    category: 'bim',
    categoryLabel: CATEGORY_LABELS.bim,
    description: 'Proprietary Autodesk Revit BIM building project database.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Autodesk Revit API (Proprietary)',
    status: 'COMING_SOON',
    validation: 'OLE2 / Compound Storage containing Revit preview or database streams',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'Proprietary Revit project format. Please export from Revit to IFC, DWG, or DXF for full conversion.',
  },
  {
    extension: 'std',
    name: 'STAAD.Pro Structural Model',
    mimeType: 'text/plain',
    category: 'structural',
    categoryLabel: CATEGORY_LABELS.structural,
    description: 'Bentley STAAD.Pro structural analysis and design command file.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['json', 'txt', 'dxf'],
    engine: 'STAAD Command Parser (In Development)',
    status: 'COMING_SOON',
    validation: 'Starts with STAAD SPACE or STAAD PLANE commands',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'STAAD structural model command parser is in development. Will export 3D wireframe nodes and members to DXF and JSON.',
  },
  {
    extension: 'edb',
    name: 'CSI ETABS Database',
    mimeType: 'application/octet-stream',
    category: 'structural',
    categoryLabel: CATEGORY_LABELS.structural,
    description: 'Computers and Structures ETABS building analysis model database.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'CSI ETABS Engine (Proprietary)',
    status: 'COMING_SOON',
    validation: 'Binary ETABS database structure',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Proprietary structural analysis format. Export to .e2k text format or DXF/IFC for conversion.',
  },
  {
    extension: 'sdb',
    name: 'CSI SAP2000 Structural Database',
    mimeType: 'application/octet-stream',
    category: 'structural',
    categoryLabel: CATEGORY_LABELS.structural,
    description: 'Computers and Structures SAP2000 finite element model database.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'CSI SAP2000 Engine (Proprietary)',
    status: 'COMING_SOON',
    validation: 'Binary SAP2000 database structure',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Proprietary finite element model database. Export to .s2k text file or DXF for conversion.',
  },

  // ==================== 10. ADOBE CREATIVE SUITE ====================
  {
    extension: 'psd',
    name: 'Adobe Photoshop Document',
    mimeType: 'image/vnd.adobe.photoshop',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'Layered raster graphics document with color channels, clipping paths, and masks.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['png', 'jpg', 'webp', 'pdf'],
    engine: 'ag-psd High-Precision Photoshop Engine',
    status: 'SUPPORTED',
    validation: 'Magic bytes 8BPS (0x38 0x42 0x50 0x53)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses Adobe Photoshop layered design composites into transparent PNG, high-density JPG, or print-ready PDF files.',
  },
  {
    extension: 'ai',
    name: 'Adobe Illustrator Artwork',
    mimeType: 'application/postscript',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'Vector graphics file created with Adobe Illustrator.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['pdf', 'png', 'jpg'],
    engine: 'Adobe Illustrator Dual-Stream Vector Engine',
    status: 'SUPPORTED',
    validation: 'Contains PDF stream %PDF or PostScript %!PS-Adobe with Illustrator tags',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: true,
    conversionNotes: 'Renders Illustrator vector artwork and design layout paths from PDF-compatible streams into print-ready PDF or high-DPI raster images.',
  },
  {
    extension: 'eps',
    name: 'Encapsulated PostScript',
    mimeType: 'application/postscript',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'PostScript vector graphics format used for print publication and vector exchange.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['pdf', 'png', 'jpg'],
    engine: 'Ghostscript & PostScript Vector Engine',
    status: 'SUPPORTED',
    validation: 'PostScript header %!PS-Adobe or binary EPS header (0xC5 0xD0 0xD3 0xC6)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Renders vector paths, typography, and graphics from .EPS files into crisp high-DPI raster images or lossless vector PDF documents.',
  },
  {
    extension: 'aep',
    name: 'Adobe After Effects Project',
    mimeType: 'application/vnd.adobe.aftereffects.project',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'Adobe After Effects motion graphics and visual effects project.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'After Effects Rendering Engine (Requires Adobe Host)',
    status: 'COMING_SOON',
    validation: 'RIFF....FXLM container or RIFI header',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Native conversion requires compatible Adobe software. Convert-X does not simulate fake video rendering without an authentic After Effects host.',
  },
  {
    extension: 'prproj',
    name: 'Adobe Premiere Pro Project',
    mimeType: 'application/x-premiere',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'Adobe Premiere Pro video editing timeline and sequence project.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Premiere Pro Video Engine (Requires Adobe Host)',
    status: 'COMING_SOON',
    validation: 'GZipped XML containing <PremiereData>',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'Native conversion requires Premiere Pro video rendering engine. Export timeline from Premiere as MP4 or ProRes for direct file processing.',
  },
  {
    extension: 'indd',
    name: 'Adobe InDesign Document',
    mimeType: 'application/x-indesign',
    category: 'adobe',
    categoryLabel: CATEGORY_LABELS.adobe,
    description: 'Adobe InDesign multi-page desktop publishing layout document.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'InDesign Server (Proprietary)',
    status: 'COMING_SOON',
    validation: 'Magic bytes 0x06 0x06 0xED 0xF5 0xD8 0x1D 0x46 0xE5',
    securityLevel: 'MEDIUM_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: true,
    previewSupport: false,
    conversionNotes: 'Native conversion requires InDesign software. Please export publication to IDML or PDF from InDesign for direct conversion.',
  },

  // ==================== 11. MACHINE LEARNING & AI FORMATS ====================
  {
    extension: 'safetensors',
    name: 'SafeTensors Model Weights',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Fast and secure tensor storage format developed by Hugging Face without pickle execution vulnerability.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'SafeTensors Zero-Execution Header Parser',
    status: 'SUPPORTED',
    validation: '8-byte unsigned integer header length followed by valid JSON tensor metadata',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Safely parses model architecture, tensor dimensions, shapes, dtypes, parameter counts, and metadata into structured JSON, TXT summaries, or PDF reports without running Python bytecode.',
  },
  {
    extension: 'onnx',
    name: 'Open Neural Network Exchange',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Open standard format for representing machine learning and deep learning models.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'ONNX Protocol Buffer Model Inspector',
    status: 'SUPPORTED',
    validation: 'Protocol buffer model containing ModelProto fields (ir_version, opset_import, graph)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Inspects computational graphs, opset versions, inputs/outputs tensor shapes, and layer breakdowns into structured JSON metadata or architectural PDF reports.',
  },
  {
    extension: 'tflite',
    name: 'TensorFlow Lite Model',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Lightweight format for deploying machine learning models on edge and mobile devices.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'TFLite FlatBuffers Schema Inspector',
    status: 'SUPPORTED',
    validation: 'FlatBuffers file identifier TFL3 (0x54 0x46 0x4C 0x33) at byte offset 4',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Inspects mobile model operators, tensors, subgraphs, quantizations, and buffers to JSON and PDF architecture summaries.',
  },
  {
    extension: 'h5',
    name: 'HDF5 / Keras Saved Model',
    mimeType: 'application/x-hdf5',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Hierarchical Data Format holding deep learning model architectures, weights, and optimizer states.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'HDF5 Structure & Keras Config Inspector',
    status: 'SUPPORTED',
    validation: 'Magic bytes \\x89HDF\\r\\n\\x1a\\n (0x89 0x48 0x44 0x46 0x0D 0x0A 0x1A 0x0A)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Extracts Keras model configuration, layer topologies, loss functions, and dataset metadata without executing arbitrary code.',
  },
  {
    extension: 'keras',
    name: 'Keras v3 Model Archive',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Modern Keras 3 format containing config.json, metadata.json, and tensor variables.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'Keras v3 Archive Inspector',
    status: 'SUPPORTED',
    validation: 'ZIP package containing config.json and metadata.json',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Extracts Keras 3 model topology, layer arguments, and training configurations into structured JSON and PDF reports.',
  },
  {
    extension: 'gguf',
    name: 'GPT-Generated Unified Format',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Unified file format for large language models (LLaMA, Mistral, Gemma) used by llama.cpp.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'txt', 'pdf'],
    engine: 'GGUF Binary Header & Quantization Inspector',
    status: 'SUPPORTED',
    validation: 'Magic bytes GGUF (0x47 0x47 0x55 0x46)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Inspects LLM architecture parameters, context lengths, token vocabularies, and quantization schemes (Q4_K_M, Q8_0, FP16) to JSON and PDF summaries.',
  },
  {
    extension: 'pt',
    name: 'PyTorch Model Checkpoint',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'PyTorch tensor and module state checkpoint.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['json', 'txt'],
    engine: 'Safe PyTorch Checkpoint Inspector',
    status: 'PARTIAL',
    validation: 'ZIP archive containing archive/data.pkl or raw Python pickle signature',
    securityLevel: 'HIGH_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'SECURITY NOTICE: PyTorch checkpoints contain pickled Python bytecode that can execute arbitrary system commands. Convert-X safely inspects archive headers and TorchScript configurations without unpickling bytecode. Direct model execution requires isolated microVM sandboxing.',
  },
  {
    extension: 'pth',
    name: 'PyTorch State Dict',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'PyTorch neural weights checkpoint file.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['json', 'txt'],
    engine: 'Safe PyTorch Checkpoint Inspector',
    status: 'PARTIAL',
    validation: 'ZIP archive or pickle header',
    securityLevel: 'HIGH_RISK',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'SECURITY NOTICE: Pickled weights are safely checked without executing bytecode. For model conversion, export from PyTorch using torch.onnx.export() to generate a safe .ONNX model.',
  },
  {
    extension: 'pkl',
    name: 'Python Pickle Serialization',
    mimeType: 'application/octet-stream',
    category: 'ml',
    categoryLabel: CATEGORY_LABELS.ml,
    description: 'Python object serialization protocol.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: [],
    engine: 'Pickle Opcode Disassembler (Safe Mode Only)',
    status: 'PARTIAL',
    validation: 'Pickle protocol opcode 0x80 followed by protocol version (0x02 - 0x05)',
    securityLevel: 'HIGH_RISK',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: false,
    conversionNotes: 'SECURITY WARNING: Untrusted pickle files contain arbitrary executable instructions. Convert-X will never execute unpickling in shared production environments without hardware sandboxing. Export datasets to Parquet or JSON.',
  },

  // ==================== 12. DATA SCIENCE & TABULAR ====================
  {
    extension: 'csv',
    name: 'Comma-Separated Values',
    mimeType: 'text/csv',
    category: 'datascience',
    categoryLabel: CATEGORY_LABELS.datascience,
    description: 'Standard plain text tabular data format with comma delimiter.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'jsonl', 'tsv', 'xlsx', 'xml', 'yaml'],
    engine: 'High-Performance Tabular Data Engine',
    status: 'SUPPORTED',
    validation: 'Valid RFC 4180 CSV character rows and consistent columns',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Seamless bidirectional conversion between CSV and JSON, JSONL, TSV, XLSX spreadsheets, XML records, or YAML datasets.',
  },
  {
    extension: 'tsv',
    name: 'Tab-Separated Values',
    mimeType: 'text/tab-separated-values',
    category: 'datascience',
    categoryLabel: CATEGORY_LABELS.datascience,
    description: 'Tab-delimited structured text table.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['csv', 'json', 'jsonl', 'xlsx', 'yaml'],
    engine: 'High-Performance Tabular Data Engine',
    status: 'SUPPORTED',
    validation: 'Tab-delimited columns with uniform record widths',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts TSV files into CSV, JSON arrays, JSONL, or formatted Excel spreadsheets.',
  },
  {
    extension: 'json',
    name: 'JavaScript Object Notation',
    mimeType: 'application/json',
    category: 'developer',
    categoryLabel: CATEGORY_LABELS.developer,
    description: 'Universal lightweight data interchange format.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['csv', 'tsv', 'jsonl', 'xlsx', 'yaml', 'xml'],
    engine: 'Universal JSON & Developer Engine',
    status: 'SUPPORTED',
    validation: 'Valid JSON object or array syntax',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts JSON record arrays to tabular CSV/XLSX/TSV, streaming JSONL, formatted YAML, or hierarchical XML.',
  },
  {
    extension: 'jsonl',
    name: 'JSON Lines Stream',
    mimeType: 'application/x-ndjson',
    category: 'datascience',
    categoryLabel: CATEGORY_LABELS.datascience,
    description: 'Newline-delimited JSON stream for large datasets and LLM training corpora.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'csv', 'tsv', 'yaml'],
    engine: 'Streaming JSONL Engine',
    status: 'SUPPORTED',
    validation: 'Lines containing independent valid JSON objects',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts JSON Lines streams into standard JSON arrays, tabular CSV, or formatted YAML.',
  },
  {
    extension: 'parquet',
    name: 'Apache Parquet Columnar Data',
    mimeType: 'application/vnd.apache.parquet',
    category: 'datascience',
    categoryLabel: CATEGORY_LABELS.datascience,
    description: 'Open source, columnar data file format optimized for fast analytic queries.',
    inputSupport: true,
    outputSupport: false,
    supportedOutputs: ['csv', 'json', 'tsv'],
    engine: 'hyparquet Pure JavaScript Parquet Engine',
    status: 'SUPPORTED',
    validation: 'Starts with magic bytes PAR1 (0x50 0x41 0x52 0x31)',
    securityLevel: 'SAFE',
    maxFileSize: 50 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Reads Apache Parquet columns, schemas, and record batches directly and exports to standard CSV, JSON, or TSV without native dependencies.',
  },
  {
    extension: 'yaml',
    name: 'YAML Ain’t Markup Language',
    mimeType: 'text/yaml',
    category: 'developer',
    categoryLabel: CATEGORY_LABELS.developer,
    description: 'Human-friendly data serialization language for configuration and datasets.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'csv', 'xml'],
    engine: 'js-yaml Parser & Builder',
    status: 'SUPPORTED',
    validation: 'Valid YAML document syntax',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Bidirectional conversion between YAML data and JSON, CSV, or XML.',
  },
  {
    extension: 'yml',
    name: 'YAML Data Document',
    mimeType: 'text/yaml',
    category: 'developer',
    categoryLabel: CATEGORY_LABELS.developer,
    description: 'Alternate extension for YAML data documents.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'csv', 'xml'],
    engine: 'js-yaml Parser & Builder',
    status: 'SUPPORTED',
    validation: 'Valid YAML document syntax',
    securityLevel: 'SAFE',
    maxFileSize: 25 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Converts YAML configuration trees and datasets to JSON or tabular formats.',
  },
  {
    extension: 'xml',
    name: 'Extensible Markup Language',
    mimeType: 'application/xml',
    category: 'developer',
    categoryLabel: CATEGORY_LABELS.developer,
    description: 'Standard tree-structured markup language for data interchange.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'csv', 'yaml'],
    engine: 'fast-xml-parser High-Speed Engine',
    status: 'SUPPORTED',
    validation: 'Starts with <?xml or contains valid XML root tags',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Parses structured XML tags into JSON objects, CSV tables, or formatted YAML.',
  },
  {
    extension: 'sql',
    name: 'Structured Query Language Dump',
    mimeType: 'application/sql',
    category: 'developer',
    categoryLabel: CATEGORY_LABELS.developer,
    description: 'Relational database DDL and DML statements file.',
    inputSupport: true,
    outputSupport: true,
    supportedOutputs: ['json', 'csv', 'txt'],
    engine: 'SQL INSERT Statement Extractor',
    status: 'SUPPORTED',
    validation: 'Contains SQL statements (CREATE TABLE, INSERT INTO, SELECT)',
    securityLevel: 'SAFE',
    maxFileSize: 30 * 1024 * 1024,
    multipageSupport: false,
    previewSupport: true,
    conversionNotes: 'Extracts tabular records from SQL INSERT statements into JSON arrays and CSV datasets.',
  },
];

export function getFormatDefinition(extension: string): FormatDefinition | undefined {
  const clean = extension.toLowerCase().replace(/^\./, '');
  const normalized = clean === 'jpeg' ? 'jpg' : clean === 'tif' ? 'tiff' : clean === 'htm' ? 'html' : clean;
  return FORMAT_REGISTRY.find((f) => f.extension === normalized);
}

export function getFormatsByCategory(category: FormatCategory): FormatDefinition[] {
  return FORMAT_REGISTRY.filter((f) => f.category === category);
}

export function searchFormats(query: string): FormatDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return FORMAT_REGISTRY;

  return FORMAT_REGISTRY.filter((f) => {
    return (
      f.extension.includes(q) ||
      f.name.toLowerCase().includes(q) ||
      f.category.toLowerCase().includes(q) ||
      f.categoryLabel.toLowerCase().includes(q) ||
      f.description.toLowerCase().includes(q) ||
      f.engine.toLowerCase().includes(q)
    );
  });
}
